### ISSUE TITLE
Export Graph error

### ISSUE THREAD

**Issue by rinisbet** [Azure-Samples/digital-twins-explorer#110]
Who: Alina

When exporting a graph, you receive this error:
_TypeError: this.queryTwinsPaged is not a function
    at n. (https://adtexplorer-dev1.adtexplorer-dev1-ase.p.azurewebsites.net/static/js/main.03de20f6.chunk.js:1:73911)
    at u (https://adtexplorer-dev1.adtexplorer-dev1-ase.p.azurewebsites.net/static/js/2.1f42d7c2.chunk.js:2:3639055)
    at Generator._invoke (https://adtexplorer-dev1.adtexplorer-dev1-ase.p.azurewebsites.net/static/js/2.1f42d7c2.chunk.js:2:3638843)
    at Generator.forEach.e. [as next] (https://adtexplorer-dev1.adtexplorer-dev1-ase.p.azurewebsites.net/static/js/2.1f42d7c2.chunk.js:2:3639478)
    at r (https://adtexplorer-dev1.adtexplorer-dev1-ase.p.azurewebsites.net/static/js/2.1f42d7c2.chunk.js:2:2538)
    at s (https://adtexplorer-dev1.adtexplorer-dev1-ase.p.azurewebsites.net/static/js/2.1f42d7c2.chunk.js:2:2741)
    at https://adtexplorer-dev1.adtexplorer-dev1-ase.p.azurewebsites.net/static/js/2.1f42d7c2.chunk.js:2:2800
    at new Promise ()
    at n. (https://adtexplorer-dev1.adtexplorer-dev1-ase.p.azurewebsites.net/static/js/2.1f42d7c2.chunk.js:2:2681)
    at n. (https://adtexplorer-dev1.adtexplorer-dev1-ase.p.azurewebsites.net/static/js/main.03de20f6.chunk.js:1:74112)_

**Comment by jamiewilbraham** [comment]
Hi @rinisbet,

Thanks for reporting.

I made a commit to the development branch last week that should resolve this. 

Are you able to pull the latest from that branch and check if the issue still exists?

Thanks,
Jamie

**Comment by jamiewilbraham** [comment]
Closing as the fix is now in the new default main branch here: https://github.com/Azure-Samples/digital-twins-explorer

Thanks again for reporting!
