### ISSUE TITLE
Error importing example .json files

### ISSUE THREAD

**Issue by SjoukjeZaal** [Azure-Samples/digital-twins-explorer#122]
Hi,

I'm receiving the below error when I want to import the json files from the example folder:

Error: Invalid iri I. Error: IRI scheme not specified
    at JsonldGraph.validateIRI (http://localhost:3000/static/js/vendors~main.chunk.js:140926:13)
    at JsonldGraph.expandIRI (http://localhost:3000/static/js/vendors~main.chunk.js:140252:14)
    at JsonldGraph.createVertex (http://localhost:3000/static/js/vendors~main.chunk.js:140214:29)
    at Vertex.setOutgoing (http://localhost:3000/static/js/vendors~main.chunk.js:141891:21)
    at Vertex.setType (http://localhost:3000/static/js/vendors~main.chunk.js:141923:12)
    at JsonldGraph._loadVertex (http://localhost:3000/static/js/vendors~main.chunk.js:141020:14)
    at JsonldGraph.load (http://localhost:3000/static/js/vendors~main.chunk.js:140543:16)
    at ModelService.initializeWithModels (http://localhost:3000/static/js/main.chunk.js:22546:27)
    at ModelService.getModelIdsForUpload (http://localhost:3000/static/js/main.chunk.js:22550:16)
    at ModelViewerComponent.addModels (http://localhost:3000/static/js/main.chunk.js:14973:51)
    at ModelViewerComponent.handleUpload (http://localhost:3000/static/js/main.chunk.js:14954:20)

Any idea what is happening here?

Thanks!

-Sjoukje

**Comment by jamiewilbraham** [comment]
Hi @SjoukjeZaal,

Which model are you trying to upload from the examples folder? or are you trying to upload multiple?

Thanks

**Comment by SjoukjeZaal1** [comment]
Hi,

This error is occurring when I want to upload 1 single model and when uploading multiple models. This is happening with all the models.

-Sjoukje

**Comment by SjoukjeZaal** [comment]
Hi,

This error is occurring when I want to upload 1 single model and when uploading multiple models. This is happening with all the models.

-Sjoukje

**Comment by jamiewilbraham** [comment]
Unfortunately, I cannot reproduce this issue. 

Are you able to try a fresh clone of the main branch https://github.com/Azure-Samples/digital-twins-explorer/tree/main and see if the issue is still present?

**Comment by danhellem** [comment]
@SjoukjeZaal can you get me a copy of your models that are failing on the import? You can email them to me directly if that is easier to dahellem@microsoft.com

**Comment by rinisbet** [comment]
@danhellem were you able to repro this?

**Comment by danhellem** [comment]
@rinisbet I never received any files from @SjoukjeZaal. Will need those before I can reproduce.

**Comment by SjoukjeZaal** [comment]
I sent these files to your email address, some time ago. Haven't you received them?

**Comment by danhellem** [comment]
@SjoukjeZaal I just imported them without any issues.  I suspect this is related to your instance of ADT explorer. Have you tried using the new hosted version?

https://explorer.digitaltwins.azure.net/
